using System.Reflection;

namespace Pipelines.Builder.Interfaces;

public interface IDispatcherBuilder
{
    /// <summary>
    /// Adds a specific Dispatcher Interface Type to the pipeline builder. This interface will be implemented by Dispatcher (which will be provided by Pipelines library).
    /// </summary>
    /// <typeparam name="TDispatcher">This is the Type of the Dispatcher interface to be added to the pipeline builder. This method expects a interface Type that will be implemented by Dispatcher.</typeparam>
    /// <param name="pipelineAssembly">Assembly where AddPipeline() method was executed.</param>
    /// <returns>An IDispatcherBuilder instance that allows for further pipeline configuration.</returns>
    /// <exception cref="Pipelines.Builder.Exceptions.DispatcherNotRegisteredException">The dispatcher registration is missing from the Dependency Injection Container. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/feature/troubleshooting_runtime/docs/troubleshooting.md#dispatchernotregisteredexception">documentation</a> for troubleshooting details.</exception> 
    /// <exception cref="Pipelines.Builder.Validators.Shared.InterfaceConstraint.Exceptions.ProvidedTypeIsNotInterfaceException">One of the types provided to the pipeline is not an interface. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#providedtypeisnotinterfaceexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.OnlyOneHandleMethod.Exceptions.HandlerMethodNotFoundException">A provided type doesn't define a handle method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#handlermethodnotfoundexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.OnlyOneHandleMethod.Exceptions.MultipleHandlerMethodsException">Multiple methods were defined in the provided type. Each interface must contain only a single method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#multiplehandlermethodsexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodWithOneParameter.Exceptions.MethodShouldHaveAtLeastOneParameterException">The defined Handle method does not have any parameters. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#methodshouldhaveatleastoneparameterexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Dispatcher.InputType.Exceptions.DispatcherMethodInputTypeMismatchException">The Dispatcher's Handle method does not use the expected Input type as its first parameter. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#dispatchermethodinputtypemismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodResultTypes.Exceptions.ExpectedMethodWithResultException">Given the Input generic arguments, it was anticipated that the Handler/Dispatcher would have a method returning a result, but a void was found instead. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#expectedmethodwithresultexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodResultTypes.Exceptions.ResultTypeCountMismatchException">The number of result types defined by the Input generic arguments does not match the number of result types found in the Dispatcher/Handler method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#resulttypecountmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.GenericTypeCountMismatchException">The number of constraints in the result types defined in the Handler or Dispatcher does not match. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#generictypecountmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.GenericTypeMismatchException"></exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.IsGenericMismatchException">There's a mismatch between the result types in the Handler and Dispatcher: one is generic, while the other is not. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#isgenericmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.TypeMismatchException">There's a mismatch between the non generic result types in the Handler and Dispatcher. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#typemismatchexception">documentation</a> for troubleshooting details. </exception>
    /// <exception cref="Pipelines.Builder.Validators.CrossValidation.MethodParameters.Exceptions.ParameterCountMismatchException">The Handler and Dispatcher methods have a mismatch in the number of parameters. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#parametercountmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.CrossValidation.MethodParameters.Exceptions.ParameterTypeMismatchException">There's a mismatch in the type of a parameter between the Handler and Dispatcher methods. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#parametertypemismatchexception">documentation</a> for troubleshooting details. </exception>
    /// <exception cref="Pipelines.Builder.Validators.CrossValidation.ResultType.Exceptions.ResultTypeCountMismatchException">The number of result types defined by the Input generic arguments does not match the number of result types found in the Dispatcher/Handler method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#resulttypecountmismatchexception">documentation</a> for troubleshooting details. </exception>
    /// <exception cref="Pipelines.Builder.Validators.CrossValidation.ResultType.Exceptions.TaskReturnTypeMismatchException">There's a mismatch in the return type of the Handler and Dispatcher methods. One method returns a Task<> type, while the other does not.  See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#taskreturntypemismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.CrossValidation.ResultType.Exceptions.VoidAndValueMethodMismatchException">There's an inconsistency in the return types between the Handler and Dispatcher methods. One method returns a value, while the other returns void. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#voidandvaluemethodmismatchexception">documentation</a> for troubleshooting details. </exception>
    public IPipelineDecoratorBuilder AddDispatcher<TDispatcher>(Assembly pipelineAssembly) where TDispatcher : class;
    
    /// <inheritdoc cref="AddDispatcher{TDispatcher}(Assembly)" />
    /// <param name="options">DispatcherOptions instance defining the options for dispatcher.</param>
    public IPipelineDecoratorBuilder AddDispatcher<TDispatcher>(DispatcherOptions options, Assembly pipelineAssembly) where TDispatcher : class;
}