using System.Reflection;

namespace Pipelines.Builder.Interfaces;

public interface IHandlerBuilder
{
    /// <summary>
    /// Adds a specific Handler Interface Type to the pipeline builder. This interface will be implemented by Handlers.
    /// </summary>
    /// <param name="handlerType">This is the Type of the Handler interface to be added to the pipeline builder. This method expects a interface Type that will be implemented by Handlers</param>
    /// <param name="assemblies">The Assemblies where the handlers are located</param>
    /// <returns>An IDispatcherBuilder instance that allows for further pipeline configuration.</returns>
    /// <exception cref="Pipelines.Builder.Validators.Shared.InterfaceConstraint.Exceptions.ProvidedTypeIsNotInterfaceException">One of the types provided to the pipeline is not an interface. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#providedtypeisnotinterfaceexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.OnlyOneHandleMethod.Exceptions.HandlerMethodNotFoundException">A provided type doesn't define a handle method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#handlermethodnotfoundexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.OnlyOneHandleMethod.Exceptions.MultipleHandlerMethodsException">Multiple methods were defined in the provided type. Each interface must contain only a single method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#multiplehandlermethodsexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodWithOneParameter.Exceptions.MethodShouldHaveAtLeastOneParameterException">The defined Handle method does not have any parameters. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#methodshouldhaveatleastoneparameterexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Handler.InputType.Exceptions.GenericArgumentsNotFoundException">The Handler lacks generic arguments. At least one generic argument is required, specifically for Input. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#genericargumentsnotfoundexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Handler.InputType.Exceptions.HandlerInputTypeMismatchException">The first generic argument doesn't have the Input type as its constraint. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#genericargumentsnotfoundexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Handler.InputType.Exceptions.InvalidConstraintLengthException">The first generic argument lacks constraints. At least one constraint is required, specifically for the Input type. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#invalidconstraintlengthexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodResultTypes.Exceptions.ExpectedMethodWithResultException">Given the Input generic arguments, it was anticipated that the Handler/Dispatcher would have a method returning a result, but a void was found instead. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#expectedmethodwithresultexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.MethodResultTypes.Exceptions.ResultTypeCountMismatchException">The number of result types defined by the Input generic arguments does not match the number of result types found in the Dispatcher/Handler method. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#resulttypecountmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.GenericTypeCountMismatchException">The number of constraints in the result types defined in the Handler or Dispatcher does not match. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#handlerinputtypemismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.GenericTypeMismatchException">There is a mismatch in the generic type constraints between the Handler and the Dispatcher, or between the Input result types constraint and the Handler or Dispatcher. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#generictypemismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.IsGenericMismatchException">There's a mismatch between the result types in the Handler and Dispatcher: one is generic, while the other is not. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#isgenericmismatchexception">documentation</a> for troubleshooting details.</exception>
    /// <exception cref="Pipelines.Builder.Validators.Shared.CompareTypes.Exceptions.TypeMismatchException">There's a mismatch between the non generic result types in the Handler and Dispatcher. See the <a href="https://github.com/DumplingsDevs/Pipelines/blob/main/docs/troubleshooting.md#typemismatchexception">documentation</a> for troubleshooting details. </exception>
    public IDispatcherBuilder AddHandler(Type handlerType, params Assembly[] assemblies);
}